export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const FIND_USER_START = "FIND_USER_START";
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_FAILED = "FIND_USER_FAILED";

export const ADD_NEW_GROUP_START = "ADD_NEW_GROUP_START";
export const ADD_NEW_GROUP_SUCCESS = "ADD_NEW_GROUP_SUCCESS";
export const ADD_NEW_GROUP_FAILED = "ADD_NEW_GROUP_FAILED";

export const GET_ALL_GROUP_START = "GET_ALL_GROUP_START";
export const GET_ALL_GROUP_SUCCESS = "GET_ALL_GROUP_SUCCESS";
export const GET_ALL_GROUP_FAILED = "GET_ALL_GROUP_FAILED";

export const GET_GROUP_DETAILS_START = "GET_GROUP_DETAILS_START";
export const GET_GROUP_DETAILS_SUCCESS = "GET_GROUP_DETAILS_SUCCESS";
export const GET_GROUP_DETAILS_FAILED = "GET_GROUP_DETAILS_FAILED";

export const CHANGE_ADD_GROUP_STATE = "CHANGE_ADD_GROUP_STATE";
export const CHANGE_ADD_EXPENSE_STATE = "CHANGE_ADD_EXPENSE_STATE";

export const ADD_EXPENSE_START = "ADD_EXPENSE_START";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED";
